version: '3.8'
services:
  cache:
    image: memcached:latest
    ports:
      - 11211:11211
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=url-shortener
    volumes:
      - data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
volumes:
  data:
